config/routes.rb
Rails.application.routes.draw do
  
  root "pages#home"

  get "about" => 'pages#about'

  resources :weeks, :except => [:destroy, :edit, :update] do
    resources :concepts, :only => [:new, :create]
  end

end

app/models/concept.rb
class Concept < ActiveRecord::Base
  belongs_to :week
  has_many :votes

  validates :name, :presence => true
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :concept
end

app/models/week.rb
class Week < ActiveRecord::Base
  has_many :concepts

  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController

  def new 
    @concept = Concept.new
  end

  def create
    @week = Week.find(params[:week_id])
    @concept = @week.concepts.build(concept_params)

    if @concept.save
      redirect_to week_url(@week)
    else
      redirect_to week_url(@week), :notice => "Cannot be blank"
    end
  end

  private
  def concept_params
    params.require(:concept).permit(:name)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController

  def index
    @weeks = Week.all
  end

  def new
    @week = Week.new
  end

  def create
    @week = Week.new(week_params)
    if @week.save
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @week = Week.find(params[:id])
    @concept = @week.concepts.build
  end

  private
  def week_params
    params.require(:week).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Planr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
  
</body>
</html>

app/views/pages/about.html.erb
<h1>What is Planr?</h1>

<p>Planr is tool for Bitmaker students to utilize. Simply click on the week you need help with and add a concept that you want to cover during the break-out session. Once created, vote for that concept and if others need help, they will also vote on it. Planr works on a honor-system policy at the moment - don't click more than once!</p>

app/views/pages/home.html.erb
<%= link_to "Home", root_url %>
<%= link_to "About", about_url %>

<h1>Planr: the Bitmaker Whiteboard</h1>

<%= link_to "Web Development", weeks_url %>

app/views/weeks/index.html.erb
<h1>Web Development Immersive Course</h1>

<% @weeks.each do |week| %>
  <li><%= link_to week.name, week_path(week.id) %></li>
<% end %>

app/views/weeks/new.html.erb
<h1>Create a Week</h1>
<%= form_for @week do |f| %>
  <% if @week.errors.any? %>
    <h2>Invalid Form: <%= pluralize(@week.errors.count, "error") %> prohibited sign-up success</h2>
  <% end %>
  <ul>
    <% @week.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>

  <%= f.label :name %><br>
  <%= f.text_field :name %>
  <%= f.submit "Submit" %>
  <%= link_to "Back", weeks_url %>
<% end %>

app/views/weeks/show.html.erb
<h1><%= @week.name %> Concept Help</h1>

<ul>
  <%= @week.concepts.each do |concept| %>
    <li><%= concept.name %></li>
  <% end %>
</ul>

<h3>Add a Concept</h3>
<%= form_for [@week, @concept] do |f| %>
  
  <%= f.label :name %><br>  
  <%= f.text_field :name %>
  <%= f.submit "Add" %>
<% end %>